services:
  postgres:
    image: postgres:16
    container_name: film-postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - ./backend/test:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exampleuser"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: ghcr.io/veraulitinaya/film-backend:latest
    container_name: film-backend

    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: exampleuser
      DATABASE_PASSWORD: examplepassword
      DATABASE_NAME: exampledb
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: ghcr.io/veraulitinaya/film-frontend:latest
    container_name: film-frontend
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: ghcr.io/veraulitinaya/film-nginx:latest
    container_name: film-nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/public/content/afisha:/usr/share/nginx/html/content/afisha:ro
    depends_on:
      - backend
      - frontend