server {
  listen 80 default_server;   
  server_name _;   

  root /usr/share/nginx/html;
  index index.html;

location / {
  root /usr/share/nginx/html;
  index index.html;
  try_files $uri /index.html;
}

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /content/afisha/ {
    alias /usr/share/nginx/html/content/afisha/;
    access_log off;
    expires 30d;
  }

  location /api/ {
    proxy_pass http://backend:3000;
  }
}